Repository Art-Diary/Backend, pull requests merged in 2024-07, with the labels that each got.

#179 [178 feature] 전시 검색 기록 저장 및 업데이트
  src/main/java/klieme/artdiary/exhibitions/data_access/entity/SearchEntity.java
  src/main/java/klieme/artdiary/exhibitions/data_access/repository/SearchRepository.java
  src/main/java/klieme/artdiary/exhibitions/service/SearchOperationUseCase.java
  src/main/java/klieme/artdiary/exhibitions/service/SearchService.java
  src/main/java/klieme/artdiary/exhibitions/ui/controller/SearchController.java
  src/main/java/klieme/artdiary/exhibitions/ui/request_body/SearchContentsRequest.java
Labels: feature

#181 [180feature] 전시 검색 기록 조회
  src/main/java/klieme/artdiary/exhibitions/data_access/repository/SearchRepository.java
  src/main/java/klieme/artdiary/exhibitions/service/SearchReadUseCase.java
  src/main/java/klieme/artdiary/exhibitions/service/SearchService.java
  src/main/java/klieme/artdiary/exhibitions/ui/controller/SearchController.java
  src/main/java/klieme/artdiary/exhibitions/ui/view/SearchContentView.java
Labels: feature

#185 Refactor/182 refactor 동일한 이메일을 가진 소셜 로그인 통합 구현
  src/main/java/klieme/artdiary/common/UserIdFilter.java
  src/main/java/klieme/artdiary/users/data_access/entity/SocialLoginEntity.java
  src/main/java/klieme/artdiary/users/data_access/entity/SocialLoginId.java
  src/main/java/klieme/artdiary/users/data_access/entity/UserEntity.java
  src/main/java/klieme/artdiary/users/data_access/repository/SocialLoginRepository.java
  src/main/java/klieme/artdiary/users/data_access/repository/UserRepository.java
  src/main/java/klieme/artdiary/users/service/UserOperationUseCase.java
  src/main/java/klieme/artdiary/users/service/UserService.java
  src/main/java/klieme/artdiary/users/ui/controller/UserController.java
Labels: refactor

#187 186-refactor-전시회-검색-기록-삭제-uri-변경
  src/main/java/klieme/artdiary/exhibitions/data_access/repository/SearchRepository.java
  src/main/java/klieme/artdiary/exhibitions/service/SearchOperationUseCase.java
  src/main/java/klieme/artdiary/exhibitions/service/SearchService.java
  src/main/java/klieme/artdiary/exhibitions/ui/controller/SearchController.java
Labels: refactor

#189 188-refactor-전시회-검색-기록-조회-response-data-변경
  src/main/java/klieme/artdiary/exhibitions/service/SearchReadUseCase.java
  src/main/java/klieme/artdiary/exhibitions/service/SearchService.java
  src/main/java/klieme/artdiary/exhibitions/ui/view/SearchContentView.java
Labels: refactor

#191 [bug] 전시회 리뷰 썸네일 반환 데이터 오류
  src/main/java/klieme/artdiary/exhibitions/service/ExhService.java
Labels: bug

#194 [193feature]검색-기록-가장-최근-시간순으로-정렬
  src/main/java/klieme/artdiary/exhibitions/service/SearchService.java
Labels: feature

#200 [refactor] mydiary 파트에 새로운 전시방문 및 기록 엔티티 적용
  src/main/java/klieme/artdiary/common/ImageTransfer.java
  src/main/java/klieme/artdiary/common/ImageType.java
  src/main/java/klieme/artdiary/record_data_access/entity/DiaryEntity.java
  src/main/java/klieme/artdiary/record_data_access/repository/DiaryRepoCustom.java
  src/main/java/klieme/artdiary/record_data_access/repository/DiaryRepoCustomImpl.java
  src/main/java/klieme/artdiary/record_data_access/repository/DiaryRepository.java
  src/main/java/klieme/artdiary/record_data_access/repository/ExhVisitRepoCustom.java
  src/main/java/klieme/artdiary/record_data_access/repository/ExhVisitRepoCustomImpl.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryOperationUseCase.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryReadUseCase.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryService.java
  src/main/java/klieme/artdiary/solo/ui/controller/MyDiaryController.java
  src/main/java/klieme/artdiary/solo/ui/request_body/MyDiaryRequest.java
  src/main/java/klieme/artdiary/solo/ui/request_body/MyDiaryUpdateRequest.java
  src/main/java/klieme/artdiary/solo/ui/view/MyDiaryView.java
  src/main/java/klieme/artdiary/user/service/UserService.java
Labels: refactor

#202 [refactor] calendar 파트에 새로운 전시방문 및 기록 엔티티 적용
  src/main/java/klieme/artdiary/calendar/info/ScheduleInfo.java
  src/main/java/klieme/artdiary/calendar/service/CalendarService.java
  src/main/java/klieme/artdiary/record_data_access/repository/ExhVisitRepoCustom.java
  src/main/java/klieme/artdiary/record_data_access/repository/ExhVisitRepoCustomImpl.java
Labels: refactor

#204 [refactor] gathering 파트에 새로운 전시방문 및 기록 엔티티 적용
  src/main/java/klieme/artdiary/gathering/info/ExhibitionInfo.java
  src/main/java/klieme/artdiary/gathering/service/GatheringOperationUseCase.java
  src/main/java/klieme/artdiary/gathering/service/GatheringReadUseCase.java
  src/main/java/klieme/artdiary/gathering/service/GatheringService.java
  src/main/java/klieme/artdiary/gathering/ui/controller/GatheringController.java
  src/main/java/klieme/artdiary/gathering/ui/view/GatheringDiaryView.java
  src/main/java/klieme/artdiary/gathering/ui/view/GatheringExhView.java
  src/main/java/klieme/artdiary/record_data_access/repository/DiaryRepoCustom.java
  src/main/java/klieme/artdiary/record_data_access/repository/DiaryRepoCustomImpl.java
  src/main/java/klieme/artdiary/record_data_access/repository/ExhVisitRepository.java
Labels: refactor

#206 [refactor] user 파트에 새로운 전시방문 및 기록 엔티티 적용
  src/main/java/klieme/artdiary/gathering/service/GatheringService.java
  src/main/java/klieme/artdiary/record_data_access/entity/DiaryEntity.java
  src/main/java/klieme/artdiary/record_data_access/entity/ExhVisitEntity.java
  src/main/java/klieme/artdiary/record_data_access/repository/DiaryRepository.java
  src/main/java/klieme/artdiary/record_data_access/repository/ExhVisitRepository.java
  src/main/java/klieme/artdiary/user/service/UserService.java
Labels: refactor

#212 Refactor/211 refactor mate 파트에 새로운 전시방문 및 기록 엔티티 적용
  src/main/java/klieme/artdiary/gathering/service/GatheringReadUseCase.java
  src/main/java/klieme/artdiary/gathering/service/GatheringService.java
  src/main/java/klieme/artdiary/gathering/ui/view/GatheringDiaryView.java
  src/main/java/klieme/artdiary/mate/service/MateExhReadUseCase.java
  src/main/java/klieme/artdiary/mate/service/MateExhService.java
  src/main/java/klieme/artdiary/mate/service/MateExhsService.java
  src/main/java/klieme/artdiary/mate/ui/controller/MateExhsController.java
  src/main/java/klieme/artdiary/mate/ui/view/MateDiaryView.java
  src/main/java/klieme/artdiary/mate/ui/view/MateExhsView.java
  src/main/java/klieme/artdiary/record_data_access/entity/DiaryEntity.java
  src/main/java/klieme/artdiary/record_data_access/repository/DiaryRepoCustom.java
  src/main/java/klieme/artdiary/record_data_access/repository/DiaryRepoCustomImpl.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryReadUseCase.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryService.java
  src/main/java/klieme/artdiary/solo/service/MyExhService.java
Labels: refactor

#213 Feature/192 feature jwt 적용
  build.gradle
  src/main/java/klieme/artdiary/calendar/service/CalendarService.java
  src/main/java/klieme/artdiary/calendar/ui/controller/CalendarController.java
  src/main/java/klieme/artdiary/common/SecurityConfig.java
  src/main/java/klieme/artdiary/common/SecurityUtil.java
  src/main/java/klieme/artdiary/common/UserIdFilter.java
  src/main/java/klieme/artdiary/common/WebConfig.java
  src/main/java/klieme/artdiary/common/api/ApiErrorView.java
  src/main/java/klieme/artdiary/common/api/ApiExceptionHandler.java
  src/main/java/klieme/artdiary/common/api/ArtDiaryException.java
  src/main/java/klieme/artdiary/common/api/MessageType.java
  src/main/java/klieme/artdiary/common/image/ImageTransfer.java
  src/main/java/klieme/artdiary/common/image/ImageType.java
  src/main/java/klieme/artdiary/common/jwt/CustomAccessDeniedHandler.java
  src/main/java/klieme/artdiary/common/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/klieme/artdiary/common/jwt/CustomUserDetails.java
  src/main/java/klieme/artdiary/common/jwt/CustomUserDetailsService.java
  src/main/java/klieme/artdiary/common/jwt/JwtFilter.java
  src/main/java/klieme/artdiary/common/jwt/JwtUtil.java
  src/main/java/klieme/artdiary/common/jwt/TokenInfo.java
  src/main/java/klieme/artdiary/exhibition/service/ExhService.java
  src/main/java/klieme/artdiary/exhibition/service/SearchService.java
  src/main/java/klieme/artdiary/exhibition/ui/controller/ExhController.java
  src/main/java/klieme/artdiary/favoriteexh/service/FavoriteExhService.java
  src/main/java/klieme/artdiary/gathering/service/GatheringService.java
  src/main/java/klieme/artdiary/mate/service/MateExhService.java
  src/main/java/klieme/artdiary/mate/service/MateService.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryService.java
  src/main/java/klieme/artdiary/solo/service/MyExhService.java
  src/main/java/klieme/artdiary/solo/ui/controller/MyDiaryController.java
  src/main/java/klieme/artdiary/user/data_access/entity/UserEntity.java
  src/main/java/klieme/artdiary/user/service/UserOperationUseCase.java
  src/main/java/klieme/artdiary/user/service/UserReadUseCase.java
  src/main/java/klieme/artdiary/user/service/UserService.java
  src/main/java/klieme/artdiary/user/ui/controller/UserController.java
  src/main/java/klieme/artdiary/user/ui/request_body/TesterRequest.java
  src/main/java/klieme/artdiary/user/ui/request_body/UpdateTokenRequest.java
  src/main/java/klieme/artdiary/user/ui/view/AccessTokenView.java
  src/main/java/klieme/artdiary/user/ui/view/UserView.java
Labels: refactor, feature

#217 [refactor] 로컬 대신 aws s3에 사진 업로드로 변경
  build.gradle
  src/main/java/klieme/artdiary/calendar/service/CalendarService.java
  src/main/java/klieme/artdiary/common/FormatDate.java
  src/main/java/klieme/artdiary/common/S3Config.java
  src/main/java/klieme/artdiary/common/image/S3ImageTransfer.java
  src/main/java/klieme/artdiary/exhibition/service/ExhReadUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/ExhService.java
  src/main/java/klieme/artdiary/exhibition/ui/controller/ExhController.java
  src/main/java/klieme/artdiary/favoriteexh/service/FavoriteExhReadUseCase.java
  src/main/java/klieme/artdiary/favoriteexh/service/FavoriteExhService.java
  src/main/java/klieme/artdiary/favoriteexh/ui/controller/FavoriteExhController.java
  src/main/java/klieme/artdiary/gathering/service/GatheringOperationUseCase.java
  src/main/java/klieme/artdiary/gathering/service/GatheringReadUseCase.java
  src/main/java/klieme/artdiary/gathering/service/GatheringService.java
  src/main/java/klieme/artdiary/gathering/ui/controller/GatheringController.java
  src/main/java/klieme/artdiary/mate/service/MateExhReadUseCase.java
  src/main/java/klieme/artdiary/mate/service/MateExhService.java
  src/main/java/klieme/artdiary/mate/service/MateOperationUseCase.java
  src/main/java/klieme/artdiary/mate/service/MateReadUseCase.java
  src/main/java/klieme/artdiary/mate/service/MateService.java
  src/main/java/klieme/artdiary/mate/ui/controller/MateController.java
  src/main/java/klieme/artdiary/mate/ui/controller/MateExhsController.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryOperationUseCase.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryReadUseCase.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryService.java
  src/main/java/klieme/artdiary/solo/service/MyExhReadUseCase.java
  src/main/java/klieme/artdiary/solo/service/MyExhService.java
  src/main/java/klieme/artdiary/solo/ui/controller/MyDiaryController.java
  src/main/java/klieme/artdiary/user/service/UserOperationUseCase.java
  src/main/java/klieme/artdiary/user/service/UserReadUseCase.java
  src/main/java/klieme/artdiary/user/service/UserService.java
  src/main/java/klieme/artdiary/user/ui/controller/UserController.java
Labels: refactor

#220 Refactor/218 refactor 기록 내용에 첨부된 사진 저장
  src/main/java/klieme/artdiary/common/image/S3ImageTransfer.java
  src/main/java/klieme/artdiary/fcm/SendAlarmService.java
  src/main/java/klieme/artdiary/record_data_access/entity/DiaryEntity.java
  src/main/java/klieme/artdiary/record_data_access/repository/ExhVisitRepoCustom.java
  src/main/java/klieme/artdiary/record_data_access/repository/ExhVisitRepoCustomImpl.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryOperationUseCase.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryService.java
  src/main/java/klieme/artdiary/solo/ui/controller/MyDiaryController.java
  src/main/java/klieme/artdiary/solo/ui/request_body/MyDiaryRequest.java
  src/main/java/klieme/artdiary/solo/ui/request_body/MyDiaryUpdateRequest.java
  src/main/java/klieme/artdiary/user/service/UserService.java
Labels: refactor

#222 [221 refactor] 전시회 상세정보 중 기록 조회 수정
  src/main/java/klieme/artdiary/exhibition/service/ExhReadUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/ExhService.java
  src/main/java/klieme/artdiary/exhibition/ui/view/AllDiaryOfExhIdView.java
  src/main/java/klieme/artdiary/record_data_access/repository/DiaryRepoCustom.java
  src/main/java/klieme/artdiary/record_data_access/repository/DiaryRepoCustomImpl.java
Labels: refactor
