Repository Art-Diary/Backend, pull requests merged in 2024-08, with the labels that each got.

#224 [feature] 전시회 등록 틀 만들기
  src/main/java/klieme/artdiary/common/FormatDate.java
  src/main/java/klieme/artdiary/exhibition/data_access/entity/RegExhEntity.java
  src/main/java/klieme/artdiary/exhibition/data_access/repository/RegExhRepository.java
  src/main/java/klieme/artdiary/exhibition/regExhApi.txt
  src/main/java/klieme/artdiary/exhibition/service/RegExhOperationUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhReadUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhService.java
  src/main/java/klieme/artdiary/exhibition/ui/controller/RegExhController.java
  src/main/java/klieme/artdiary/exhibition/ui/request_body/RegExhByAdminRequest.java
  src/main/java/klieme/artdiary/exhibition/ui/request_body/RegExhByUserRequest.java
  src/main/java/klieme/artdiary/exhibition/ui/view/RegExhListView.java
  src/main/java/klieme/artdiary/exhibition/ui/view/RegExhView.java
  src/main/java/klieme/artdiary/fcm/SendAlarmService.java
Labels: feature

#229 [feature] 등록할 전시회 목록 조회(사용자/관리자)
  src/main/java/klieme/artdiary/exhibition/data_access/repository/RegExhCustom.java
  src/main/java/klieme/artdiary/exhibition/data_access/repository/RegExhCustomImpl.java
  src/main/java/klieme/artdiary/exhibition/data_access/repository/RegExhRepository.java
  src/main/java/klieme/artdiary/exhibition/regExhApi.txt
  src/main/java/klieme/artdiary/exhibition/service/RegExhReadUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhService.java
  src/main/java/klieme/artdiary/exhibition/ui/controller/RegExhController.java
Labels: feature

#232 [feature] 등록할 전시회 삭제(사용자)
  src/main/java/klieme/artdiary/exhibition/data_access/entity/RegExhEntity.java
  src/main/java/klieme/artdiary/exhibition/data_access/repository/RegExhRepository.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhService.java
  src/main/java/klieme/artdiary/user/service/UserService.java
Labels: feature

#235 Feature/228 feature 전시회 등록 요청 확인 코멘트 추가 및 전시회 정보 수정 (관리자)
  src/main/java/klieme/artdiary/exhibition/data_access/entity/RegExhEntity.java
  src/main/java/klieme/artdiary/exhibition/data_access/repository/RegExhCustomImpl.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhOperationUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhService.java
  src/main/java/klieme/artdiary/exhibition/ui/controller/RegExhController.java
  src/main/java/klieme/artdiary/exhibition/ui/request_body/RegExhByAdminRequest.java
Labels: feature

#236 [234 feature] 등록할 전시회 수정사용자
  src/main/java/klieme/artdiary/exhibition/data_access/entity/RegExhEntity.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhOperationUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhService.java
  src/main/java/klieme/artdiary/exhibition/ui/controller/RegExhController.java
Labels: feature

#237 Refactor/225 refactor 권한 추가
  src/main/java/klieme/artdiary/calendar/service/CalendarService.java
  src/main/java/klieme/artdiary/common/SecurityUtil.java
  src/main/java/klieme/artdiary/common/image/ImageTransfer.java
  src/main/java/klieme/artdiary/common/image/S3ImageTransfer.java
  src/main/java/klieme/artdiary/common/jwt/CustomUserDetails.java
  src/main/java/klieme/artdiary/exhibition/service/ExhService.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhService.java
  src/main/java/klieme/artdiary/exhibition/service/SearchService.java
  src/main/java/klieme/artdiary/favoriteexh/service/FavoriteExhService.java
  src/main/java/klieme/artdiary/gathering/service/GatheringService.java
  src/main/java/klieme/artdiary/mate/service/MateExhService.java
  src/main/java/klieme/artdiary/mate/service/MateService.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryService.java
  src/main/java/klieme/artdiary/solo/service/MyExhService.java
  src/main/java/klieme/artdiary/user/data_access/entity/UserEntity.java
  src/main/java/klieme/artdiary/user/enums/RoleType.java
  src/main/java/klieme/artdiary/user/service/UserReadUseCase.java
  src/main/java/klieme/artdiary/user/service/UserService.java
  src/main/java/klieme/artdiary/user/ui/view/UserView.java
Labels: refactor

#239 [233 feature] 등록할 전시회 하나 조회사용자
  src/main/java/klieme/artdiary/exhibition/service/RegExhReadUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhService.java
Labels: feature

#240 [refactor] 사용자가 등록한 전시회를 포함한 전시회 리스트 반환 순서 추가
  src/main/java/klieme/artdiary/exhibition/data_access/entity/ExhEntity.java
  src/main/java/klieme/artdiary/exhibition/data_access/entity/RegExhEntity.java
  src/main/java/klieme/artdiary/exhibition/data_access/repository/ExhRepoCustom.java
  src/main/java/klieme/artdiary/exhibition/data_access/repository/ExhRepoCustomImpl.java
  src/main/java/klieme/artdiary/exhibition/data_access/repository/RegExhCustom.java
  src/main/java/klieme/artdiary/exhibition/data_access/repository/RegExhCustomImpl.java
  src/main/java/klieme/artdiary/exhibition/service/ExhService.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhService.java
Labels: refactor

#242 [bug] 전시회 등록 요청 데이터 중 포스터 데이터 타입 변경
  src/main/java/klieme/artdiary/common/image/ImageType.java
  src/main/java/klieme/artdiary/common/image/S3ImageTransfer.java
  src/main/java/klieme/artdiary/exhibition/regExhApi.txt
  src/main/java/klieme/artdiary/exhibition/service/RegExhOperationUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhService.java
  src/main/java/klieme/artdiary/exhibition/ui/controller/RegExhController.java
  src/main/java/klieme/artdiary/exhibition/ui/request_body/RegExhByAdminRequest.java
  src/main/java/klieme/artdiary/exhibition/ui/request_body/RegExhByUserRequest.java
Labels: bug
