Repository Art-Diary/Backend, pull requests merged in 2024-03, with the labels that each got.

#121 [feature] 사용자 정보 조회
  src/main/java/klieme/artdiary/users/service/UserReadUseCase.java
  src/main/java/klieme/artdiary/users/service/UserService.java
  src/main/java/klieme/artdiary/users/ui/controller/UserController.java
  src/main/java/klieme/artdiary/users/ui/view/UserView.java
Labels: feature

#118 [feature] 사용자 프로필 설정 기능 구현
  src/main/java/klieme/artdiary/common/ImageTransfer.java
  src/main/java/klieme/artdiary/mydiarys/service/MydiaryService.java
  src/main/java/klieme/artdiary/users/data_access/entity/UserEntity.java
  src/main/java/klieme/artdiary/users/data_access/repository/UserRepository.java
  src/main/java/klieme/artdiary/users/service/UserOperationUseCase.java
  src/main/java/klieme/artdiary/users/service/UserReadUseCase.java
  src/main/java/klieme/artdiary/users/service/UserService.java
  src/main/java/klieme/artdiary/users/ui/controller/UserController.java
  src/main/java/klieme/artdiary/users/ui/request_body/UserUpdateRequest.java
  src/main/java/klieme/artdiary/users/ui/view/UserView.java
Labels: feature

#123 [feature] 사용자 알림1,2,3 설정 업데이트 기능 구현
  src/main/java/klieme/artdiary/users/data_access/entity/UserEntity.java
  src/main/java/klieme/artdiary/users/service/UserOperationUseCase.java
  src/main/java/klieme/artdiary/users/service/UserReadUseCase.java
  src/main/java/klieme/artdiary/users/service/UserService.java
  src/main/java/klieme/artdiary/users/ui/controller/UserController.java
  src/main/java/klieme/artdiary/users/ui/request_body/UserAlarmRequest.java
  src/main/java/klieme/artdiary/users/ui/view/UserAlarmView.java
Labels: feature

#124 [feature] 닉네임 중복 확인
  src/main/java/klieme/artdiary/users/service/UserReadUseCase.java
  src/main/java/klieme/artdiary/users/service/UserService.java
  src/main/java/klieme/artdiary/users/ui/controller/UserController.java
  src/main/java/klieme/artdiary/users/ui/request_body/UserNicknameRequest.java
  src/main/java/klieme/artdiary/users/ui/view/UserNicknameView.java
Labels: feature

#128 [refactor] 탈퇴 회원의 기록 및 기록의 공개 여부 고려
  src/main/java/klieme/artdiary/common/ImageTransfer.java
  src/main/java/klieme/artdiary/exhibitions/service/ExhService.java
  src/main/java/klieme/artdiary/gatherings/service/GatheringService.java
  src/main/java/klieme/artdiary/mateexhs/service/MateExhsService.java
Labels: bug, refactor

#129 Feature/127 feature 사용자 탈퇴
  src/main/java/klieme/artdiary/exhibitions/data_access/entity/UserExhEntity.java
  src/main/java/klieme/artdiary/gatherings/data_access/entity/GatheringDiaryEntity.java
  src/main/java/klieme/artdiary/users/data_access/entity/ReasonEntity.java
  src/main/java/klieme/artdiary/users/data_access/repository/ReasonRepository.java
  src/main/java/klieme/artdiary/users/service/UserOperationUseCase.java
  src/main/java/klieme/artdiary/users/service/UserService.java
  src/main/java/klieme/artdiary/users/ui/controller/UserController.java
  src/main/java/klieme/artdiary/users/ui/request_body/DeleteReasonRequest.java
Labels: feature

#131 [feature] 간단한 프론트엔드 연결 코드
  src/main/java/klieme/artdiary/common/WebConfig.java
Labels: feature

#133 [bug] 한 전시회에 대하여 캘린더에 저장된 날짜 조회 응답 데이터 오류 발견
  src/main/java/klieme/artdiary/myexhs/info/StoredDateInfo.java
  src/main/java/klieme/artdiary/myexhs/service/MyExhsReadUseCase.java
  src/main/java/klieme/artdiary/myexhs/service/MyExhsService.java
  src/main/java/klieme/artdiary/myexhs/ui/controller/MyExhsController.java
  src/main/java/klieme/artdiary/myexhs/ui/view/MyStoredDateView.java
Labels: bug

#135 [refactor] 기록 수정 중 방문 날짜 수정 적용
  src/main/java/klieme/artdiary/common/ImageTransfer.java
  src/main/java/klieme/artdiary/gatherings/data_access/entity/GatheringDiaryEntity.java
  src/main/java/klieme/artdiary/mydiarys/data_access/entity/MydiaryEntity.java
  src/main/java/klieme/artdiary/mydiarys/service/MydiaryService.java
  src/main/java/klieme/artdiary/mydiarys/ui/controller/MydiaryController.java
  src/main/java/klieme/artdiary/users/service/UserService.java
Labels: refactor
