Repository Art-Diary/Backend, pull requests merged in 2024-12, with the labels that each got.

#263 Feature/262 feature 전시회 상세 정보 수정 api 추가
  src/main/java/klieme/artdiary/common/image/S3ImageTransfer.java
  src/main/java/klieme/artdiary/exhibition/data_access/entity/ExhEntity.java
  src/main/java/klieme/artdiary/exhibition/service/ExhOperationUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/ExhService.java
  src/main/java/klieme/artdiary/exhibition/ui/controller/ExhController.java
  src/main/java/klieme/artdiary/exhibition/ui/request_body/ExhRequest.java
  src/main/java/klieme/artdiary/solo/ui/controller/MyDiaryController.java
  src/main/java/klieme/artdiary/solo/ui/request_body/MyDiaryRequest.java
  src/main/java/klieme/artdiary/solo/ui/request_body/MyDiaryUpdateRequest.java
Labels: feature

#265 [refactor] 모임의 방문 날짜 정보에 모임 정보 추가
  .gitignore
  src/main/java/klieme/artdiary/exhibition/service/ExhReadUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/ExhService.java
  src/main/java/klieme/artdiary/exhibition/ui/view/StoredDateView.java
Labels: refactor

#267 [bug] 전시회 리뷰 중 탈퇴 사용자의 전시회 모임 정보 없는 것 해결
  src/main/java/klieme/artdiary/exhibition/service/ExhReadUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/ExhService.java
  src/main/java/klieme/artdiary/gathering/service/GatheringReadUseCase.java
  src/main/java/klieme/artdiary/gathering/service/GatheringService.java
Labels: bug

#269 [refactor] 전시 메이트 목록 정렬 닉네임 순으로 수정
  src/main/java/klieme/artdiary/mate/data_access/repository/MateRepoCustom.java
  src/main/java/klieme/artdiary/mate/data_access/repository/MateRepoCustomImpl.java
  src/main/java/klieme/artdiary/mate/data_access/repository/MateRepository.java
  src/main/java/klieme/artdiary/mate/service/MateService.java
Labels: refactor

#271 [refactor] 모임 목록을 사용자가 모임에서 최근에 전시회를 방문한 날짜 순 정렬로 수정
  src/main/java/klieme/artdiary/gathering/data_access/repository/GatheringMateRepoCustom.java
  src/main/java/klieme/artdiary/gathering/data_access/repository/GatheringMateRepoCustomImpl.java
  src/main/java/klieme/artdiary/gathering/data_access/repository/GatheringMateRepository.java
  src/main/java/klieme/artdiary/gathering/service/GatheringService.java
Labels: refactor

#273 [refactor] 전시 메이트 검색 시 메이트가 아닌 유저 리스트와 이미 친구인 유저 리스트로 반환하고 닉네임 순으로 정렬…
  src/main/java/klieme/artdiary/mate/data_access/repository/MateRepoCustom.java
  src/main/java/klieme/artdiary/mate/data_access/repository/MateRepoCustomImpl.java
  src/main/java/klieme/artdiary/mate/service/MateReadUseCase.java
  src/main/java/klieme/artdiary/mate/service/MateService.java
  src/main/java/klieme/artdiary/mate/ui/controller/MateController.java
  src/main/java/klieme/artdiary/mate/ui/view/MateSearchView.java
Labels: refactor

#276 [274 feature]검색기록 10개 이상일 시, 가장 오래된 기록 삭제
  src/main/java/klieme/artdiary/exhibition/service/SearchService.java
Labels: feature

#277 [refactor] 모임 메이트 검색 시 새로 추가할 유저 리스트와 이미 포함된 유저 리스트로 반환하고 닉네임 순으로 정렬로 변경
  src/main/java/klieme/artdiary/gathering/data_access/repository/GatheringMateRepoCustom.java
  src/main/java/klieme/artdiary/gathering/data_access/repository/GatheringMateRepoCustomImpl.java
  src/main/java/klieme/artdiary/gathering/service/GatheringReadUseCase.java
  src/main/java/klieme/artdiary/gathering/service/GatheringService.java
  src/main/java/klieme/artdiary/gathering/ui/controller/GatheringController.java
  src/main/java/klieme/artdiary/gathering/ui/view/GatheringMateSearchView.java
  src/main/java/klieme/artdiary/mate/service/MateService.java
  src/main/java/klieme/artdiary/mate/ui/controller/MateController.java
Labels: refactor

#279 [feature] 외부 서버 터널링
  build.gradle
  src/main/java/klieme/artdiary/ArtdiaryApplication.java
  src/main/java/klieme/artdiary/common/SSHConnection.java
  src/main/java/klieme/artdiary/common/SshTunnelConfig.java
Labels: feature

#281 [refactor] 모임이 방문한 전시회를 방문 날짜 기준 최신순 정렬로 수정
  src/main/java/klieme/artdiary/gathering/data_access/repository/GatheringMateRepoCustomImpl.java
  src/main/java/klieme/artdiary/gathering/info/ExhibitionInfo.java
  src/main/java/klieme/artdiary/gathering/service/GatheringService.java
  src/main/java/klieme/artdiary/record_data_access/repository/DiaryRepoCustomImpl.java
Labels: refactor

#288 [refactor] 사진 데이터가 널인 경우 반영
  src/main/java/klieme/artdiary/exhibition/data_access/entity/ExhEntity.java
  src/main/java/klieme/artdiary/exhibition/data_access/entity/RegExhEntity.java
  src/main/java/klieme/artdiary/exhibition/service/ExhService.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhOperationUseCase.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhService.java
  src/main/java/klieme/artdiary/exhibition/ui/controller/RegExhController.java
  src/main/java/klieme/artdiary/exhibition/ui/request_body/ExhRequest.java
  src/main/java/klieme/artdiary/exhibition/ui/request_body/RegExhByAdminRequest.java
  src/main/java/klieme/artdiary/exhibition/ui/request_body/RegExhByUserRequest.java
  src/main/java/klieme/artdiary/solo/service/MyDiaryService.java
  src/main/java/klieme/artdiary/user/data_access/entity/UserEntity.java
  src/main/java/klieme/artdiary/user/service/UserService.java
  src/main/java/klieme/artdiary/user/ui/request_body/UserUpdateRequest.java
Labels: refactor

#290 [refactor] 사용자의 등록 전시회 목록을 등록 현황에 우선순위를 두고 최신순으로 정렬
  src/main/java/klieme/artdiary/exhibition/data_access/repository/RegExhCustom.java
  src/main/java/klieme/artdiary/exhibition/data_access/repository/RegExhCustomImpl.java
  src/main/java/klieme/artdiary/exhibition/service/RegExhService.java
Labels: refactor

#295 [294 refactor] 전시회-정렬-수정
  src/main/java/klieme/artdiary/exhibition/data_access/repository/ExhRepoCustomImpl.java
Labels: refactor

#297 [269 refactor] 전시회 옵션-선택시-정렬-수정
  src/main/java/klieme/artdiary/exhibition/data_access/repository/ExhRepoCustomImpl.java
Labels: refactor

#299 [298 refactor] 검색어로-검색시-각-필드별-가나다순-정렬
  src/main/java/klieme/artdiary/exhibition/data_access/repository/ExhRepoCustomImpl.java
Labels: refactor

#300 [refactor] 새로 초대 받은 모임 및 모임에 추가된 전시 방문 날짜 푸시 알림 추가
  src/main/java/klieme/artdiary/common/SchedulerConfig.java
  src/main/java/klieme/artdiary/common/push_alarm/PushAlarm.java
  src/main/java/klieme/artdiary/fcm/FcmSendDto.java
  src/main/java/klieme/artdiary/fcm/SendAlarmService.java
  src/main/java/klieme/artdiary/gathering/data_access/repository/GatheringMateRepoCustom.java
  src/main/java/klieme/artdiary/gathering/data_access/repository/GatheringMateRepoCustomImpl.java
  src/main/java/klieme/artdiary/gathering/service/GatheringOperationUseCase.java
  src/main/java/klieme/artdiary/gathering/service/GatheringService.java
  src/main/java/klieme/artdiary/gathering/ui/controller/GatheringController.java
Labels: feature

#303 [302 feature] Qna 폴더 생성
  src/main/java/klieme/artdiary/qna/data_access/entity/QnaEntity.java
  src/main/java/klieme/artdiary/qna/data_access/repository/QnaRepository.java
  src/main/java/klieme/artdiary/qna/service/QnaOperationUseCase.java
  src/main/java/klieme/artdiary/qna/service/QnaReadUseCase.java
  src/main/java/klieme/artdiary/qna/service/QnaService.java
  src/main/java/klieme/artdiary/qna/ui/controller/QnaController.java
Labels: feature

#305 [304 feature] qna 폴더 추가
  src/main/java/klieme/artdiary/qna/ui/request_body/QnaRequest.java
  src/main/java/klieme/artdiary/qna/ui/view/QnaView.java
Labels: feature

#308 [307feature]q&a 상세조회
  src/main/java/klieme/artdiary/qna/service/QnaReadUseCase.java
  src/main/java/klieme/artdiary/qna/service/QnaService.java
  src/main/java/klieme/artdiary/qna/ui/controller/QnaController.java
Labels: feature

#310 [309feature]q&a수정
  src/main/java/klieme/artdiary/qna/service/QnaOperationUseCase.java
  src/main/java/klieme/artdiary/qna/service/QnaService.java
  src/main/java/klieme/artdiary/qna/ui/controller/QnaController.java
Labels: feature
